# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='stripe_transaction_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
