# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
