# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20190901_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': (('cant_have_wallet', "User can't have a wallet."),)},
        ),
    ]
