# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_paymentintent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='debit',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='ammount',
            new_name='amount',
        ),
    ]
