# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_auto_20190908_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
