# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
