# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-24 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': (('can_update_status', 'Update Issue status.'),)},
        ),
    ]
