# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_edit_all_comments', "Edit any user's comments."),)},
        ),
    ]
