# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20190825_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': (('can_update_status', 'Update Issue status.'), ('can_edit_all_issues', "Edit any user's issue"))},
        ),
        migrations.AddField(
            model_name='issue',
            name='edited',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
