# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20190826_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Bug', 'Bug Report'), ('Feature', 'Feature Request')], default='Bug', max_length=7),
        ),
    ]
