# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_vote_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created'], 'permissions': (('can_update_status', 'Update Ticket status.'), ('can_edit_all_tickets', "Edit any user's ticket"))},
        ),
    ]
