# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190925_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
