# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20191014_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approved',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='doing',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='done',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
